### ISSUE TITLE
About ：CUDA out of memory（align.py)

### ISSUE THREAD

**Issue by zweny** [nju-websoft/FAN#1]
GPU:GeForce RTX 3090 *1
memory: 23.70 GiB total capacity 
batch_size : 16/32/64/160 
--------
After run ‘python run.py and infer.py ’  successfully, i can't run './align.sh' because the error 'out of memory'.
I have tried to modify the parameters of batch_size, but failed.
So could you tell me  how to work it or the recommended requirement about GPU Memory.

**Comment by koala-222** [comment]
We use two Nvidia V100 GPUs (32G * 2), one way is freezing the top layers of BERT and only fine-tune the last layer, which reduces the cost of memory of GPUs.
