### ISSUE TITLE
questions to run the code

### ISSUE THREAD

**Issue by skorani** [nju-websoft/FAN#3]
Hi, I have many questions about your amazing paper. would you help me, please?
Would you please upload or give me the link to the dataset?
Do your code just work on the CPU? I mean you never test CUDA?
Do you split the dataset to run codes?

Thanks in advance

**Comment by koala-222** [comment]
hi~
FAN works on GPU devices.
You can find the mined data at [https://drive.google.com/file/d/1ZSkQCD2wZeAyGNbwsL-cvnOU-B2dyBeS/view?usp=sharing](https://drive.google.com/file/d/1ZSkQCD2wZeAyGNbwsL-cvnOU-B2dyBeS/view?usp=sharing)
